apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
    - ./components/yelb-ui/yelb-ui.yaml
    - ./components/redis-server/redis-server.yaml
    - ./components/yelb-db/yelb-db.yaml
    - ./components/yelb-appserver/yelb-appserver.yaml
    - ./groups/org.yaml
    - ./systems/yelb/yelb-system.yaml
    - ./resources/yelb-db-resource.yaml
    - ./domains/cloudapps-domain.yaml
